sudo: false
language: go
go:
- tip
go_build: --ldflags '-extldflags "-static" -s -w'
branches:
  only:
  - master
before_deploy:
  - ls -lah
env:
  global:
    secure: I2giYwvSUPJgtKbTLmpv8IYulHBOinyAVjbATILw+WaGk6yKbpWR1kgxyyqDjgGp8FsvV3np0N6m40E7lTWSjFrQwtgK6gwJH7TY1hbINaQzAYqfIryS7BjVXdQWzwQYYXHVY28HuXBoP2GoBGeqZWmV8szvdsXcUvsVzpfk8e70Hcnj/rZ8v+ZMIa6gCLZLfTI8HSvi5+mzvX9lV55Z4pvza81KI9zFkmEb/h55K9/k56xtENtba1XhlpKqhiIShfOQLKKvCEpOn4cfPeE0dHhks+Wi6BSE+zCiAKHFyHMjsDGqrtSbLpHmuTm56oBNHtaB3WWRAF5TGwCtIkMf17uU49c2KNjW5SpY6VFgcMlJMGatRPMVBV54nWidcRVZ+BYttEYlKj2SN8/mQcAphWREoAacTNIKUZPNBDPr2vhkCOQXyL89ht9H14Iwa4TTZKHO4/J88Bpt59p29W0kh+mHgmTwzDCoB17v3hl0xoDf7w8LOQ6FQ6Wz5m5kbTo5f86xr6KlreyE96z6WFI6mcnTWvfeOxXJiODQkMrrdDGJFdxCcdwVhxiHuwCPpDMhMOhvvX6f4cDlij8GoZy7jJsKNhWjP/jylKT+IImx+9YSNUruvaPYZT9cdNgBy9c05QbijzDldyEiMf86DcRcZKJmmciQydYC6TaLHgQrUjc=
notifications:
  email: false
  slack:
    secure: O8SlAMj1l/TT5ZLrAMUPp5P5fhrxljqiWrshFGdTtC3jMM9Hcqc8ew9fXCDjVtpb3u0krh6LxqAos2C7l8QoIOpceEKPaEM/OWQQh3lSG3q3SvctKi9+7lW0wwoV/YN5ERa69N/LFOyX6UBLb3pupAKk4tJMwJq71iSlLQ+LHtDpwVNVRXhJXwcDxODTaiHPyp4DRxkJIyDk5RDberjdfEHLBTjLkHUkCqOYCZICeAHMSdniJsCbiYOVaYNti+UbqF7GX6L+W41vy33jYT/hHA+VGMbPDAujIEGOtwsXaNIFZjfr3QTekHNtcXJ+kk8URJsT2Xf7XHD6kYvKTuXtIyrVy0mIM78bxFzUkZZO0ql4N/XhjlrqjJMoejlbP3YV8ZMKOMIjV48DxqhvwtAO1AzfVhY4ZI1kCl3mr91WKrLrKQw0VhNUdQvWoG3edP/BFWQrW4u2kVs8crh5qJhfk/KyWMb3DzjEs2bLd13jas6DGgbH8zRc3jhCHEnjF2f70X0cWKkZjvwg5KVxZYY2DxoyrZ1IAU1x8lxSm6azU72JOrCbFwQjUpR9ZONWCuiABK6hM9YkQVyArO7vV84VfQ6SQA5a4/55pWGEDDERxkr1onbslbJyCZYnA+l3yf3izeN+yMm5bhVhyve+zkXeLMDfP5pyw15eWD4dQmC4bso=
